# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = ${UNREAL_PATH}
GAMEPROJECTFILE =${PWD}/ToonTanks.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	ToonTanks-Linux-DebugGame  \
	ToonTanks-Linux-Shipping  \
	ToonTanks \
	ToonTanksEditor-Linux-DebugGame  \
	ToonTanksEditor-Linux-Shipping  \
	ToonTanksEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ToonTanksEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ToonTanksEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

ToonTanks-Linux-DebugGame:
	 $(PROJECTBUILD) ToonTanks Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ToonTanks-Linux-Shipping:
	 $(PROJECTBUILD) ToonTanks Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ToonTanks:
	 $(PROJECTBUILD) ToonTanks Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ToonTanksEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ToonTanksEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ToonTanksEditor-Linux-Shipping:
	 $(PROJECTBUILD) ToonTanksEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ToonTanksEditor:
	 $(PROJECTBUILD) ToonTanksEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
